### ISSUE TITLE
"dictionary keys changed during iteration" when running checkout_externals

### ISSUE THREAD

**Issue by christophergeiger3** [ESMCI/manage_externals#135]
### Summary of Issue:
This was a simple issue but I was stuck on it for a while, so I wanted to share how I fixed it here, in case anyone else faced the same one.

I ran into an error when trying to run `checkout_externals` for the first time on my local machine, as described here: https://escomp.github.io/CESM/release-cesm2/downloading_cesm.html

```bash
git clone -b release-cesm2.1.1 https://github.com/ESCOMP/CESM.git my_cesm_sandbox
cd my_cesm_sandbox
./manage_externals/checkout_externals
```
Produces:
```
Processing externals description file : Externals.cfg
Checking status of externals: cam, dictionary keys changed during iteration
```
It turns out that `checkout_externals` needs to be run with python 2, which may not be the default on your machine anymore, now that python 2 has passed end-of-life. 

I fixed the issue by doing:
```
python2 ./manage_externals/checkout_externals
```

**Comment by billsacks** [comment]
Thank you very much for opening this issue. I'm actually going to go ahead and reopen it, because it does seem to be a true issue.

I have reproduced this issue with python 3.8.1. `manage_externals` *should* work with python3, but it seems that there was a behavior change in python 3.8 relative to 3.7 that is causing this problem. I'll dig a bit and try to determine a fix.
