### ISSUE TITLE
Parsing variables into Externals.cfg

### ISSUE THREAD

**Issue by jkuang-exploro** [ESMCI/manage_externals#142]

**Comment by gold2718** [comment]
One of the main features of manage_externals is to provide a clear and complete description of a project that includes sub-repositories. Including a feature that causes `checkout_externals` to load a different set of repositories or repository commits depending on who calls the routine seems diametrically opposed to this vital feature. 

Many of us, in our distributed workflow, will either modify Externals.cfg or create a copy which points to our personal development forks during the development process. This does not require any new feature.

**Comment by ekluzek** [comment]
I agree with @gold2718 we actually want the versions and repositories hardcoded, so that everyone gets exactly the same codebase. And they only get something different when they've intentionally modified the Externals file. When I modify the externals file to point to my own fork, I ONLY modify the externals that I need to change for my project -- I would never want to modify them all at once.

@JianKuang-NOAA  the one exception to that is if you meant to say that variables could be used to point to specific strings (like say $github = https://github.com, or $escomp = https://github.com/ESCOMP), that would then be used later in the Externals file. I can see that angle, but because these files in general are so small I don't think that it's worth adding.
