### ISSUE TITLE
Add comments explaining the CESM.cfg and CLM.cfg files

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/manage_externals#3]
We need comments in the CESM.cfg and CLM.cfg explaining what they are, what they do, and how they are used.

**Comment by bandre-ucar** [comment]
Please annotate these files with your desired example text:

1. CESM.cfg for clm standalone
```CFG
# comment
[cism]
tag = trunk_tags/cism2_1_37
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/glc
local_path = components/cism
required = True

[clm]
protocol = externals_only
local_path = .
externals = CLM.xml
required = True

[mosart]
tag = trunk_tags/mosart1_0_26
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/mosart
local_path = components/mosart
required = True

[rtm]
tag = rtm1_0_62
protocol = git
repo_url = git@github.com:bandre-ucar/rtm-experimental.git
local_path = components/rtm
required = False

[cime]
tag = mvertens/updates_for_clm.tag2
protocol = git
repo_url = https://github.com/CESM-Development/cime/
local_path = cime
required = True

[externals_description]
version = 1.0.0
```
2. CLM.cfg
```CFG
[fates]
tag = fates_s1.0.0_a1.0.0
protocol = git
repo_url = https://github.com/NCAR/fates-release
local_path = src/fates
required = True

[ptclm]
tag = trunk_tags/PTCLM2_170706
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/PTCLM
local_path = tools/PTCLM
required = False

[externals_description]
version = 1.0.0
```

**Comment by bandre-ucar** [comment]
Another request was that we have functionality to generate or update an externals file from an existing externals file and the working directories.

The python config file parser ignores comments. So, when we read in an existing file, update the contents and write it back out, all comments will be lost. Adding comments to these will require manually updating them, or regenerating them and then manually merging the contents to preserve comments.

Maybe we should consider a different form of documentation for these files...?

**Comment by bandre-ucar** [comment]
We discussed this issue in the meeting last week:

Given that internal comments will be ignored and removed by the configuration file reader/writer, placing comments in the file is not a viable long term documentation solution.

The fields in the configuration files attempt to be self explanatory from their names, especially in the context of an existing file that is being modified. People should be referred to the documentation if they encounter a problem, and the documentation improved as issues are raised.

Since this issue is about placing documentation comments in the config file, I'm closing as resolved - won't fix.
