### ISSUE TITLE
New protocol for softlink to local disk

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/manage_externals#44]
### Summary of Issue:

My current workflow for CESM development is to set up a CESM sandbox where `components/pop` is a softlink to a local SVN checkout of POP (and in that checkout, POP's `externals/marbl/` directory is another softlink to a git checkout of MARBL). I could use `manage_externals` to checkout my POP branch directly, but I would still need to update the MARBL checkout manually... so it would be nice to have the option of doing something like

```
[pop]
tag = none
protocol = softlink
repo_url = /path/to/pop
local_path = components/pop
required = True
```

### Expected behavior and actual behavior:

Expected behavior would be a directory structure where `components/pop/` is a softlink to `/path/to/pop`, but instead I get

```
Processing externals description file : CESM.cfg

ERROR: Unknown repository protocol "softlink" in "pop".
```

### Steps to reproduce the problem (should include model description file(s) or link to public repository):

In [ESCOMP/cesm](https://github.com/ESCOMP/cesm):

```
$ git diff
 [pop]
 tag = trunk_tags/cesm_pop_2_1_20171008
-protocol = svn
+protocol = softlink
 repo_url = https://svn-ccsm-models.cgd.ucar.edu/pop2
 local_path = components/pop
 required = True
```
### What is the changeset ID of the code, and the machine you are using:

Tested on MARBL, using `cesm2_0_beta07.002` tag of ESCOMP/cesm

### have you modified the code? If so, it must be committed and available for testing:

N/A

### Screen output or log file showing the error message and context:

see above

**Comment by mnlevy1981** [comment]
Does this tool support recursive use? If POP used `manage_externals` (would need buy-in from the oceanography section, so not a short-term fix), then I could set up `POP.cfg` in my branch to populate `externals/MARBL/` from the correct git branch... but at least in the short term I could use this tool on my POP branch and go back to `svn:externals` when merging to the trunk.

**Comment by billsacks** [comment]
@mnlevy1981 yes this tool supports recursive use, and that's how we'll be using it for CLM (including FATES as an external).

As for the larger issue: I'd vote for avoiding adding 'softlink' as a protocol, because its semantics would be very different from those of svn or git, which I'm guessing would add complexity to both the user interface and the implementation. Instead, would it work to simply comment out the POP section and make your own symbolic link? If you'd prefer something more official-feeling, I could imagine having some way to denote a given external as being ignored from the point of view of this tool (you'd still create your own sym link in this case).

**Comment by mnlevy1981** [comment]
@billsacks I think setting up recursive use on my branch will be an easier (and cleaner) implementation that commenting stuff out of the `.cfg` file, so I'll look into that when I get to a stopping point in my current work. I guess I'll see how it goes when I try to merge my POP changes upstream later and need to ignore the manage_externals stuff, but that's a problem for future-me :)
