### ISSUE TITLE
Checkout hangs when subversion password is missing.

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/manage_externals#79]
### Summary of Issue:
Hangs doing a checkout when subversion password is missing.

### Expected behavior and actual behavior:
Tried doing a checkout on a new system that I've never used subversion on before.  It hangs when trying
to checkout ww3.  Should be prompted to enter your subversion username and password.  I was able to get around this by doing a manual checkout of ww3 and entering my password and saving it.  Since my password is now saved, the checkout works.

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):
Remove .subversion from your home directory.

### What is the changeset ID of the code, and the machine you are using:
Release manic-v0.7.0 

### have you modified the code? If so, it must be committed and available for testing:
No

### Screen output or log file showing the error message and context:
login1.stampede2(79)$ ./manage_externals/checkout_externals 
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CLM.cfg
Processing externals description file : Externals_POP.cfg
Processing externals description file : Externals_CISM.cfg
Checking status of externals: clm, fates, ptclm, mosart, ww3, cime, cice, pop, cvmix, marbl, cism, source_cism, rtm, cam, 
Checking out externals: clm, mosart, ww3,

**Comment by bandre-ucar** [comment]
It's 'hanging' because it is waiting for the user to enter the password. It can be entered in the terminal and it will be passed through to svn. My previous attempts to process the svn output on the fly to prompt the user were unsuccessful. I will look into it again.

There was a warning in the original documentation, but it looks like it never made it to the cesm doc. In the mean time, please update the CESM documentation with something like:
```
checkout_externals requires access to git and svn repositories that
require authentication. checkout_externals may pass through
authentication requests, but it will not cache them for you. For the
best and most robust user experience, you should have svn and git
working without password authentication. See:

    https://help.github.com/articles/connecting-to-github-with-ssh/

    ???? http://svnbook.red-bean.com/en/1.7/svn.serverconfig.netmodel.html

```

**Comment by bandre-ucar** [comment]
For security reasons svn and git do not use standard in/out/error to request and process authentication. Instead, they use lower level system interfaces like getpasswd() or special libraries. Python calling a subprocess can only interact with stdio, and can not intercept or even detect the request for authentication via lower level calls. On some systems, these requests are visible to the user, on some systems they are not. When subprocess commands expect user input they will wait and manage_externals appears to hang.

I don't think there is anything that can be done to 'fix' this from manage_externals. There may be a terminal setting that is available to users but I not have found it.

The *best* thing to do is ensure that users know they need to setup password-less access to private repos as documented above.

For now the only software fix is to change the subprocess calls to polling the running process and checking the current run length. If the run time exceeds a timeout limit, then we display a message suggesting that the user verify authentication and then declare a fatal error.

The default timeout interval of 5 minutes is probably too long and can be shortened. But since svn requires network interaction and some large checkouts can take a long time, this is a 'conservative' initial value.

**Comment by bandre-ucar** [comment]
I don't think there is anything more I can do for this. I'm going to close the issue.
