### ISSUE TITLE
Status incorrectly reports in-sync when you have made commits in detached head state

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#86]
### Summary of Issue:

If you are in detached head state at the tag given in the externals config file, then make a commit (so you are still in detached head state, but no longer at the given tag), `checkout_externals -S` says that you're in sync when in fact you are not.

I think the problem is that `RE_DETACHED` in `repository_git.py` (`RE_DETACHED = re.compile(r'\* \((?:[\w]+[\s]+)?detached (?:at|from) ([\w\-./]+)\)')`) looks at a line like this from `git branch -vv`:

```
* (HEAD detached from cime5.4.0-alpha.24) 402131faa add to readme
```

It takes the string after `detached from` as giving where you are. But it seems like the correct thing to do is:

- If it says `detached at`, then use the current behavior. (This seems important so that we get the tag name that you're on.)

- If it says `detached from`, then the string after `detached from` seems to be irrelevant; instead, use the commit hash after the parentheses. I did something like this in #69 , where I changed RE_DETACHED to `r'\* \((?:[\w]+[\s]+)?detached (?:at|from) ([\w\-./]+)\)[\s]+([\w]+)')`. But I think the correct thing to do is to actually have two separate regexes: Rename the current `RE_DETACHED` to `RE_DETACHED_AT`, and only match `detached at`, and then have a new `RE_DETACHED_FROM`, which matches `detached from` and has only one capture group: the second capture group from the version I had in #69 .

Note that if you actually run `checkout_externals` without the status flag, you end up in the correct state, since `checkout_externals` runs the `git checkout` command even if it thinks you're already in sync. But I still think it's important to fix this problem.

### Expected behavior and actual behavior:

Expected behavior: status says you're out-of-sync in the above situation

Actual behavior: status says you're in-sync in the above situation

### Steps to reproduce the problem (should include model description file(s) or link to public repository):

```
git clone git@github.com:ESCOMP/cism-wrapper.git
cd cism-wrapper
git checkout cism2_1_50
# Replace manage_externals with your desired version for testing, or keep it as is
./manage_externals/checkout_externals
cd cime
echo "some change" >> README.md
git commit -am "add to readme"
cd ..
./manage_externals/checkout_externals -S -v
```

### What is the changeset ID of the code, and the machine you are using:

I have tried this with both:

- the head of #84 (195c1d0)

- manic-v0.8.0 (the default in the above cism tag)

Both exhibit this problem

### have you modified the code? If so, it must be committed and available for testing:

No

### Screen output or log file showing the error message and context:

```
[roo2:~/temporary/cism-wrapper]$ ./manage_externals/checkout_externals -S -v
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CISM.cfg
Processing externals description file : Externals_CLM.cfg
Checking status of externals: cism, source_cism, mosart, ctsm, fates, ptclm, cime,
    ./cime
        clean sandbox, on cime5.4.0-alpha.24
    ./components/clm
        clean sandbox, on clm4_5_18_r274
    ./components/clm/src/fates
        clean sandbox, on fates_s1.4.1_a3.0.0_rev2
    ./components/clm/tools/PTCLM
        clean sandbox, on PTCLM2_171216c
    ./components/mosart
        clean sandbox, on mosart1_0_30
    ./glimmer-cism
        clean sandbox, on cism/branch_tags/longer_var_list_tags/longer_var_list_n01_cism2_1_develop_n02
```

despite:

```
[roo2:~/temporary/cism-wrapper/cime]$ git describe
cime5.4.0-alpha.24-1-g7bac08598
[roo2:~/temporary/cism-wrapper/cime]$ git branch -vv
* (HEAD detached from cime5.4.0-alpha.24) 7bac08598 add to readme
```

**Comment by billsacks** [comment]
@bandre-ucar I'm not sure if you'll have time to work on this. It would be great if you did, but I realize you may have some other things to wrap up. If you don't, it would be helpful to at least get your thoughts on how it should be fixed: Does my proposed fix sound like a reasonable way to go?

**Comment by billsacks** [comment]
I've been wondering if this logic might be more robust and easier to maintain if we did a more substantial overhaul of the logic in `_check_sync_logic`. Currently, this runs a single git command (`git branch -vv`) and then uses regex matching to parse the output to determine everything we need to know about where we are. Would it work to change this around so that we used the most appropriate git command for each case (branch/tag/hash). i.e., something like:

```python
if self._branch:
    # Run a git command to determine if we're on the correct branch
elif self._tag:
    # Run a git command to determine if we're on the correct tag
elif self._hash:
    # Run a git command to determine if we're on the correct hash
else:
    # Abort
```

@bandre-ucar do you have any thoughts on this?

**Comment by bandre-ucar** [comment]
I need to think about this some more and look at some additional output, especially regarding the regexp change. But here's my initial thoughts....

My *gut instinct* is that the added complexity of the separate regexp doesn't help and it can be handled by processing the groups of a single regexp. But that opinion is *not* informed by reproducing the error and stepping through the code to see what is going on. I may be wrong.

In general having multiple paths for branch, tag, and hash makes it harder to maintain and understand the resulting behavior. I've been aiming for normalizing all the cases and using generic logic as much as possible. So my gut instinct is to keep pushing toward a generic solution.

For a *version control tool* where we unambiguously want a simple rule like "always make the working copy match the description" then that ultimately boils down to verifying the underlying hash of both the current and desired ref are the same. In that case, then I *think* a small tweak to the logic in  GH-84 is the correct solution: always convert both the expected and current ref to the underlying hash with revparse and assert to the underlying hashes are equal.

Since the community seems to be moving away from a version control tool toward a checkout utility with a less strict and more complex set of expected behaviors, the solution is ultimately going to depend on what they define 'in-sync' to mean. My above solution is going apply to branches as well; it will report a branch as being out of sync if we're on a tracking branch but on a different commit. So for this the generic solution probably isn't going to be correct, and a more complicated special case solution is going to be needed, e.g. only check the underlying hash if we are not on a branch. But... what if the user really wants to know if they are exactly in sync with the remote...? So your proposed changes to `_check_sync_logic()` may be the correct direction to go.

**Comment by billsacks** [comment]
@bandre-ucar thanks for your thoughts on this. I like your proposed solution:

> For a *version control tool* where we unambiguously want a simple rule like "always make the working copy match the description" then that ultimately boils down to verifying the underlying hash of both the current and desired ref are the same. In that case, then I *think* a small tweak to the logic in  GH-84 is the correct solution: always convert both the expected and current ref to the underlying hash with revparse and assert to the underlying hashes are equal.

That feels like a consistent and robust mechanism. I think that would even be appropriate logic for determining in vs. out-of-sync after the proposed changes in #34 – it's just that, with #34 , we'll need some special purpose logic for branches once we determine that we're out-of-sync with the specified remote branch.

Do you think you'll have time to make the necessary changes that you proposed here?

**Comment by bandre-ucar** [comment]
I'll see what I can do.
